name: Profile Summary Cards
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@v0.1.3
        with:
          username: CodeAritra
          theme: tokyonight
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to stats branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: stats
          build_dir: profile-summary-card-output
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
